create table if not exists boards (
  id varchar(255) primary key,
  name varchar(255) not null,
  headline varchar(255) not null,
  version bigint
);

create table if not exists cards (
  pk bigint generated by default as identity primary key,
  id varchar(255) not null,
  label varchar(255) not null,
  href varchar(2048) not null,
  board_id varchar(255) not null,
  position integer,
  constraint fk_cards_board
    foreign key (board_id) references boards(id) on delete cascade
);

create table if not exists widgets (
  id bigint generated by default as identity primary key,
  board_id varchar(255) not null,
  type varchar(255) not null,
  title varchar(255) not null,
  layout varchar(255) not null,
  config_json varchar(4000) not null,
  enabled boolean not null,
  sort_order integer not null,
  constraint fk_widgets_board
    foreign key (board_id) references boards(id) on delete cascade
);

create table if not exists click_events (
  id bigint generated by default as identity primary key,
  board_id varchar(255) not null,
  card_id varchar(255) not null,
  occurred_at timestamp with time zone not null,
  source_ip varchar(255) not null
);

create table if not exists view_events (
  id bigint generated by default as identity primary key,
  board_id varchar(255) not null,
  occurred_at timestamp with time zone not null,
  source_ip varchar(255) not null,
  source varchar(255) not null,
  device_type varchar(255) not null
);

create index if not exists idx_cards_board_id on cards(board_id);
create index if not exists idx_widgets_board_sort on widgets(board_id, sort_order);
create index if not exists idx_click_events_board on click_events(board_id);
create index if not exists idx_click_events_board_card on click_events(board_id, card_id);
create index if not exists idx_click_events_board_occurred on click_events(board_id, occurred_at);
create index if not exists idx_view_events_board on view_events(board_id);
create index if not exists idx_view_events_board_occurred on view_events(board_id, occurred_at);
